apiVersion: v1
kind: Service
metadata:
  name: tgi-service
  namespace: {{ .Values.release.namespace }}
spec:
  selector:
    app: tgi
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
