apiVersion: v1
kind: Secret
metadata:
  name: azure-file-secret
  namespace: {{ .Values.release.namespace }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storageAccountName | b64enc | quote }}
  azurestorageaccountkey:  {{ .Values.storageAccountKey | b64enc | quote }}