release:
  namespace: default

image:
  repository: devacr0wsery.azurecr.io/text-generation-inference # TODO: need to be dynamic
  tag: 3.1.0
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: "2"
    memory: "10Gi"
  limits:
    cpu: "4"
    memory: "14Gi"

model:
  id: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

persistence:
  enabled: true
  size: 20Gi
  storageClass: azurefile-csi
  mountPath: "/data"


storageAccountName: ""
storageAccountKey: ""