image:
  repository: ghcr.io/huggingface/text-generation-inference
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "4"
    memory: "10Gi"
  limits:
    cpu: "4"
    memory: "14Gi"

model:
  id: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

persistence:
  enabled: true
  size: 20Gi
  storageClass: azurefile-csi
  mountPath: "/data"

