apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi
  namespace: {{ .Release.Namespace }}
  labels:
    app: tgi
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: tgi
  template:
    metadata:
      labels:
        app: tgi
    spec:
      nodeSelector:
        agentpool: userpool
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: tgi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--model-id"
            - "{{ .Values.model.id }}"
          env:
            - name: MODEL_ID
              value: "{{ .Values.model.id }}"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: model-storage
              mountPath: "{{ .Values.persistence.mountPath }}"
              readOnly: false
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
      volumes:
        - name: model-storage
          azureFile:
            secretName: azure-file-secret
            shareName: modeldata
            readOnly: false
