apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tgi-model-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany  # Azure File Share supports multiple readers
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
