apiVersion: v1
kind: Service
metadata:
  name: tgi-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tgi
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
